### ISSUE TITLE
PlistDemo/MyThemes.swift:10:8: Missing required module 'minizip'

### ISSUE THREAD

**Issue by YouYII** [jiecao-fm/SwiftTheme#1]
把代码拉下来编译 plistdemo好像跑不起来啊..
![image](https://cloud.githubusercontent.com/assets/5754760/15321262/ebbb531c-1c67-11e6-90d6-8cd7e2cdc3f7.png)
![image](https://cloud.githubusercontent.com/assets/5754760/15321276/012aa63a-1c68-11e6-9656-e7ae99ac92e0.png)

**Comment by wxxsw** [comment]
谢谢你的反馈！

我已经将Demo改为使用cocoapods管理，并更换了Demo中使用的Zip库，麻烦你重新下载试一下
