### ISSUE TITLE
用Storyboard的时候, 一个页面有很多Label, 怎么快速改变所有label的夜间颜色呢?总不会至于100多个label全部拖吧

### ISSUE THREAD

**Issue by Elgins** [jiecao-fm/SwiftTheme#11]
除了label, static tableviewcell,如果有很多怎么一致性的改变背景颜色呢?, 静态cell太多的话也不好一个一个拖啊

**Comment by wxxsw** [comment]
一个一个拖就是我们正在采用的方式，因为相比需要设置数据的控件，只有一小部分是仅作为装饰的控件，所以即便不设置主题大部分控件也是要拖的，所以这对我们来说不是问题。

但是对于你所描述的情况可能并不是非常友好，我能给出的建议有：

如果你使用plist设置主题，那么可以增加下面这种extension
```swift
extension UIView {
    
    @IBInspectable
    var backgroundColorKeyPath: String? {
        get {
            return nil
        }
        set {
            guard let newValue = newValue else { return }
            theme_backgroundColor = ThemeColorPicker(keyPath: newValue)
        }
    }
    
}
```
这是一个简单的包装，@IBInspectable可以使属性加入到属性检查器中。
这样你就可以直接在Storyboard的属性检查器中设置backgroundColor的keyPath，而不需要拖到代码中设置。
（PS：因为我的机器比较老，使用@IBInspectable时打开属性检查器会卡，所以我没有把这个特性加到这个项目中...）

另一种情况就是如果你是使用索引设置主题，因为是使用数组设置，样式的数量是不确定的，这种必须在代码中设置，拖控件是免不了的，但如果你使用统一的样式并且在同一页面中的话，可以使用IBOutletCollection。

希望能帮到你 :)

**Comment by Elgins** [comment]
many thks， 用你写的库基本上解决了夜间模式的问题， 希望这个库好好维护，以后做项目必不可少啊

**Comment by wxxsw** [comment]
😊 好的，谢谢你的支持，这个库还会继续改进的！

我先Close了，如果后续遇到问题，可以Reopen或者新开一个Issue 😇
