### ISSUE TITLE
为什么这么多的内存泄漏

### ISSUE THREAD

**Issue by jxncwzb** [jiecao-fm/SwiftTheme#15]
如图

<img width="1081" alt="a" src="https://cloud.githubusercontent.com/assets/23024637/19636266/dee32a8c-99fa-11e6-9d38-d6c91ec1b80e.png">

**Comment by wxxsw** [comment]
@jxncwzb 与我们私下交流过，此问题仅在iOS10中出现，但具体原因还不清楚

**Comment by XHJiang** [comment]
解决了么

**Comment by wxxsw** [comment]
我们认为是iOS10的Bug，如果有人知道如何规避这些内存泄漏还望告知，谢谢

**Comment by qyning** [comment]
我发现iOS10 控制器使用成员变量的闭包，然而并没有循环引用，但是也会产生内存泄漏，代码在swift2.2都正常，转swift3后，产生内存泄漏

其二：我还遇到使用-D debug 定义swift flags， debug模式的打印也出问题，release模式逃逸闭包中如果引用其他闭包一样直接崩溃
不知道是不是swift3的锅

**Comment by qyning** [comment]
我新建一个工程测试了一下
ViewController只要调用 nettool.toUpdateBlock 就会 swift_slowAlloc的内存泄漏

// VC:
class ViewController: UIViewController{
....

var nettool:NetTool!
private func updateNetData() {
    nettool = NetTool()
    nettool.toUpdateBlock = {()->Void in
        print("收到回调")
    }
}
}
// otherTool
class NetTool: NSObject {
.....
var toUpdateBlock:(()->Void)?
func toUpdate() {
toUpdateBlock?()
}
}

**Comment by qyning** [comment]
Alamofire/Alamofire#1717   Kingfisher/Kingfisher#520,看来是instrument的问题，大家都出现了这种情况
是我太紧张了。。

**Comment by shannonchou** [comment]
感谢@qyning 的调查，这个问题我们也很困惑，当初在Instruments 里发现各种第三方SDK 也会出现，也怀疑过是Instruments。
