### ISSUE TITLE
how i can get uicolor from ThemeColorPicker?

### ISSUE THREAD

**Issue by mhtranbn** [jiecao-fm/SwiftTheme#18]
Hey anwsome, how i can get value color from ThemeColorPicker? many thank for you. :)

**Comment by wxxsw** [comment]
ThemeColorPicker will not save the original value, but will save a closure, the current theme used to obtain the final value.

This is an example:
```swift
// If the current skin index is 1, the UIColor object generated according to #FFF is returned
let color = ThemeColorPicker(colors: "#000", "#FFF").value!() as? UIColor
```

**Comment by mhtranbn** [comment]
Optional(#EB4F38FF) this will return Optional(String), it will alway whitecolor.

**Comment by wxxsw** [comment]
@mhtranbn I tried it, `value ()` normal return '# EB4F38FF` corresponding UIColor object, let me see your approach?

**Comment by mhtranbn** [comment]
yup, i have tested, it ok. thank @wxxsw very much.

**Comment by wxxsw** [comment]
😄
