### ISSUE TITLE
和#11类似的问题

### ISSUE THREAD

**Issue by gitwizChen** [jiecao-fm/SwiftTheme#19]
看了[#11](https://github.com/jiecao-fm/SwiftTheme/issues/11)的问题，感觉差不多，就是一些地方的控件需要跟随夜间模式一起更改，我就扩写了UIView
```
extension UIView {
// 是否跟随主题自动切换背景色
    @IBInspectable var isThemed: Bool? {
        get {
            return false
        }
        
        set {
            guard let _ = newValue else { return }
            guard let _ = newValue else { return }
            //globalThemeCommonBackgroundColor是一个全局的颜色，大概就是夜间模式变黑色，其他则是白色
            theme_backgroundColor = newValue! ? globalThemeCommonBackgroundColor : nil
        }
    }
}
```
在StoryBoard中我勾选了一个view的Is Themed属性为On，但是在切换至夜间模式的时候并没有效果，不知道为啥，是代码的问题？

**Comment by wxxsw** [comment]
你改成下面这种写法应该就可以了（实际上只是将`Bool?`改为`Bool`）
```swift
extension UIView {
    @IBInspectable var isThemed: Bool {
        get { return false }
        set { theme_backgroundColor = newValue ? globalThemeCommonBackgroundColor : nil }
    }
}
```
---
问题的原因大概是这样的：

通过`@IBInspectable`设置的属性，实际上是间接设置了`Runtime Attributes`，如下图

<img width="259" alt="2016-12-29 8 28 04" src="https://cloud.githubusercontent.com/assets/921863/21534365/c0b74fa0-cda0-11e6-9a6f-1b872a9182b5.png">

留意图中的类型，是`Boolean`而不是`Bool`。另外，`Runtime Attributes`是在运行时调用`setValue:forKey:`来设置属性的值，可见这都是Objective-C的实现，所以通过`@IBInspectable`设置属性，仍然是通过Objective-C桥接到Swift。

但是Objective-C中的`BOOL`只有真和假，`NULL`和`nil`也被定义为假，也就没有对应Swift中`Bool?`的类型。所以基于这个原因，通过`@IBInspectable`设置`Bool`值，不能使用可选类型。

希望解决了你的问题 😄 

> 参考
[NSKeyValueCoding](https://developer.apple.com/reference/foundation/1657268-nskeyvaluecoding)
[WorkingWithCocoaDataTypes](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/WorkingWithCocoaDataTypes.html)
[BOOL / bool / Boolean / NSCFBoolean](http://nshipster.cn/bool/)

**Comment by gitwizChen** [comment]
@wxxsw 哇，真的可以了，谢谢帮忙解决问题😊。另，这个库很棒，用起来很方便💪

**Comment by fukemy** [comment]
hi, can u explain globalThemeCommonBackgroundColor? Thanks in advance
