### ISSUE TITLE
Keyboard appearance

### ISSUE THREAD

**Issue by spacedema** [jiecao-fm/SwiftTheme#22]
Hi!

Is there any plans to support .keyboardAppearance for textfields?

Thanks for great lib :)

**Comment by wxxsw** [comment]
b45415547719265da43792926be834fc9624b7f1 I added the properties you need, `theme_keyboardAppearance`.

Here are some ways to use it:
```swift
someTextField.theme_keyboardAppearance = [.default, .dark, .light]
someTextField.theme_keyboardAppearance = "somePlistKeyPath"
```

Objective-C:
```objective-c
// Note: StringStyle is not case sensitive.
someTextField.theme_keyboardAppearance = [ThemeKeyboardAppearancePicker pickerWithStringStyles:@[@"Default", @"Dark", @"Light"]];
someTextField.theme_keyboardAppearance = [ThemeKeyboardAppearancePicker pickerWithKeyPath:@"somePlistKeyPath"];
```

I noticed that if the keyboard appears while the theme is switched, the keyboard does not immediately switch the style. Reappear when it is ok, it should be the behavior of the system, for this situation you can manually resign the keyboard. Of course, I think this scene may be very rare.

**Comment by spacedema** [comment]
Great! Many thanks!

**Comment by spacedema** [comment]
Hi!

How can I update lib through cocoapods? When I'm trying pod update it says that there is no new version.

Regards

**Comment by wxxsw** [comment]
I did not release a new version, so you can specify a commit:
```ruby
pod 'SwiftTheme', :git => 'https://github.com/jiecao-fm/SwiftTheme', :commit => 'b454155'
```

**Comment by spacedema** [comment]
Thanks for the help, I'll try it
