### ISSUE TITLE
 Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.

### ISSUE THREAD

**Issue by trusk89** [jiecao-fm/SwiftTheme#24]
See title.

**Comment by trusk89** [comment]
My issue. I was setting .appearance() on UIView.

**Comment by SambathChea** [comment]
For me when I meet this warning I remove background from my 'xib' file.
hope it can help.

**Comment by JeffSchroeder** [comment]
In interface builder pull up your .xib, on the top element, in attribute inspector set the background color to default.  Then go to the Content View and set the background color there.
