### ISSUE TITLE
How can i change the image color

### ISSUE THREAD

**Issue by harsharaikkonen** [jiecao-fm/SwiftTheme#28]
I want to chane the UIImage color.

**Comment by wxxsw** [comment]
You can use theme_image to set different themes of the image, but can not change the image itself.

**Comment by wxxsw** [comment]
Because more than 1 week is not active, I closed, if there is any problem, you can reopen.

**Comment by fukemy** [comment]
i can change image color, it seem your lib is only support change image, not change color, it's will make bigger app size
