### ISSUE TITLE
Plist mode can't convert value of type 'String' to 'ThemeStatusbarStylePicker'

### ISSUE THREAD

**Issue by tomdev-biz** [jiecao-fm/SwiftTheme#29]
I'm trying to implement plist mode to my app, but I'm getting exceptions that can't convert / assign string to 'ThemeStatusBarStylePicker' / 'ThemeColorPicker'.
I have almost did same with your plist demo project, but I think I missed something.
Please help me.

**Comment by wxxsw** [comment]
If you use theme_setStatusBarStyle doesn't work as expected, you will need to `Info.plist` in `View Controller-based status bar appearence` set to `NO`.

Can you provide more information, such as showing your plist settings and related code

**Comment by tomdev-biz** [comment]
Thanks for your reply.
I have already checked #9, but no luck.

This is my plist and I will add screen shot.
`
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIAppFonts</key>
	<array>
		<string>noto-sans-bold.ttf</string>
		<string>noto-sans-regular.ttf</string>
		<string>roboto-bold.ttf</string>
		<string>roboto-light.ttf</string>
		<string>roboto-medium.ttf</string>
		<string>roboto-regular.ttf</string>
	</array>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to the photo library.</string>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to your camera.</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
`
![screen shot 2017-05-06 at 3 39 30 pm](https://cloud.githubusercontent.com/assets/26999676/25772768/3f7b43ce-3272-11e7-94e6-2666f37f0137.png)

**Comment by tomdev-biz** [comment]
The only thing I think different with your code is I have changed MyTheme.swift name to TestTheme.swift, but I think it doesn't affect to your code, right?

**Comment by wxxsw** [comment]
Yes, obviously, your code does not have any problems.

Is it possible to use the old version? The latest version is `0.3.2`

**Comment by tomdev-biz** [comment]
How can I switch the version?

**Comment by wxxsw** [comment]
If you use CocoaPods, specify the version `pod 'SwiftTheme', '0.3.2'`

**Comment by tomdev-biz** [comment]
Please let me know why you have used SSZipArchive, and should I also add it to my pod?

**Comment by wxxsw** [comment]
`SSZipArchive` is only used to demonstrate how to download zip from a remote, and then extract it into a sandbox, it is not part of `SwiftTheme`.

**Comment by tomdev-biz** [comment]
And `pod 'SwiftTheme', '0.3.2'` and `pod 'SwiftTheme', '~> 0.3.2'` shows me error .
Could you please recheck your git or update me new code?
```
[!] Unable to satisfy the following requirements:

- `SwiftTheme (= 0.3.2)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SwiftTheme (= 0.3.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by tomdev-biz** [comment]
And I have just checked my current SwiftTheme version is 0.3

**Comment by wxxsw** [comment]
You need to update the local cocoapods library using `pod repo update`.

**Comment by wxxsw** [comment]
Yes, i think so.

**Comment by tomdev-biz** [comment]
It works!
Thanks for your support.
