### ISSUE TITLE
Setting tab bar image icon and background Image

### ISSUE THREAD

**Issue by maasim94** [jiecao-fm/SwiftTheme#30]
Thanks for great library, I'm trying to add themes in my tab bar application, I've different images to set for icons, but I wasn't able to find anything to achieve this scenario

Adding a notification in sub class of UITabbar or tabbarcontroller is something in my mind , you think it's good way?

**Comment by wxxsw** [comment]
Yes, you can see about this issue in #26

**Comment by wxxsw** [comment]
For situations that require custom processing of theme changes, I plan to provide some new convenient methods, but not now.

**Comment by maasim94** [comment]
thanks :)
