### ISSUE TITLE
ThemePicker初始化方法pickerWithKeyPath的问题

### ISSUE THREAD

**Issue by vergilw** [jiecao-fm/SwiftTheme#32]
pickerWithKeyPath传入的路径有误，或者对应路径的值不存在，ThemePicker的对象仍旧会创建成功，并且没有其他属性来判断对象的值是否真实有效。这对于开发的容错处理造成了很大麻烦。本地的Plist文件因为自己控制可以完全避免，但是网络上的Plist皮肤文件就很有必要做这个处理了，App会随着更新改变Plist的结构来满足新的皮肤更改需求。这时候就涉及到新老Plist文件兼容，在这种情况下，这个容错处理逻辑变得极为重要，一不小心App就会随时崩溃。

**Comment by wxxsw** [comment]
关于你说的几点问题我解释一下：

1. `ThemePicker` 的 `pickerWithKeyPath` 在传入路径有误的时候仍然创建成功？
这个其实很好解释，正如你所说，plist 文件会从网络下载，你在设置的时候，plist 文件可能并不存在，所以这肯定是一个运行时主题切换后决定是否存在内容的对象

2. 并且没有其他属性来判断对象的值是否真实有效？
可以参考 https://github.com/jiecao-fm/SwiftTheme/issues/18 或者 https://github.com/jiecao-fm/SwiftTheme/issues/26，你是有多种方式可以直接取到值的。当然你不希望直接操作这些值，交给 `SwiftTheme` 去自动处理切换，如果值不存在，会打印一条错误日志

3. 新老 plist 文件兼容？
这个应该是 App 自身的逻辑，在更换了 `keyPath` 的时候，老的主题文件应该进行清理或者更新。当然，我并不建议随意更换 `keyPath`

4. 容错处理逻辑变得极为重要，一不小心App就会随时崩溃？
是的，谁也不希望崩溃，如果你崩溃了请告诉我。如果遇到对应的 keyPath 没有值，或者值的类型不正确无法转换，通常都会打印一条日志警告

**Comment by shabake** [comment]
oc 调用swift 有一个OCDemo的文件找不到啊

**Comment by wxxsw** [comment]
@shabake 能提供一下错误信息或者截图吗？
