### ISSUE TITLE
Cocoapods not working

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [jiecao-fm/SwiftTheme#34]
I installed the cocoapods and them tried to set the theme (plist mode) in App Delegate using following code : 

`ThemeManager.setTheme(plistName: "Red", path: .mainBundle)`

I was not able to get autocomplete predictions, as well as, on building the project, I was getting error on this line

Please help!!!

**Comment by wxxsw** [comment]
When using Cocoapods, you may need to use `import SwiftTheme` in your file.

**Comment by vaibhav-varshaaweblabs** [comment]
Did, not working

**Comment by wxxsw** [comment]
Is `use_frameworks!` In Podfile?

**Comment by vaibhav-varshaaweblabs** [comment]
Yes, it's there

**Comment by wxxsw** [comment]
I was just building locally, but everything was running normally (version 0.3.3, but it should not matter). I can not think of more possible reasons, can you send me a demo?

My mailbox is i@gesen.me

**Comment by wxxsw** [comment]
Not active and closed.
