### ISSUE TITLE
UISearchBar and UITextView  missing theme_keyboardAppearance

### ISSUE THREAD

**Issue by martinflorek** [jiecao-fm/SwiftTheme#36]
Am I missing something, again :), or there is no option to theme the keyboard appearance for `UISearchBar` and `UITextView `?

Setting search bar's `theme_barStyle ` to dark does not show a dark keyboard.

**Comment by wxxsw** [comment]
I added the property to set the appearance of the keyboard for `UISearchBar` and `UITextView`, which is missing, thanks again.

How to use: https://github.com/jiecao-fm/SwiftTheme/issues/22

Also, I did not release a new version, so you can specify a commit:
```
pod 'SwiftTheme', :git => 'https://github.com/jiecao-fm/SwiftTheme', :commit => '7aea269'
```

**Comment by martinflorek** [comment]
I am using carthage and this one works like a charm:
```
github "jiecao-fm/SwiftTheme" "7aea269"
```

Thank you again for this great library and super fast response and update!
