### ISSUE TITLE
SwiftTheme WARNING: Not found string key path

### ISSUE THREAD

**Issue by kirankunigiri** [jiecao-fm/SwiftTheme#38]
SwiftTheme WARNING: Not found string key path: Global.backgroundColor

I keep receiving this warning when I use `setTheme` in the `viewDidLoad` method. However, it is actually working fine and recognizes the Global.backgroundColor and sets it to the correct color depending on the current theme; there isn't any actual problem. I don't know how to stop this warning.

**Comment by wxxsw** [comment]
In theory, print this sentence at the same time that return nil, I can not think of other circumstances, this is a strange phenomenon. 😢

**Comment by pdobq** [comment]
Same problem for me.
