### ISSUE TITLE
这是一个伟大的项目

### ISSUE THREAD

**Issue by xhzengAIB** [jiecao-fm/SwiftTheme#4]
可以再细化一下，相信在开源贡献上会更进一步

Jack

**Comment by xhzengAIB** [comment]
1、提供UI整套解决方案
2、提供在线下发框架替换方案
3、简化使用过程（例如：UIColor：、UIImageName：），仅仅做一个方法替换的过程，不需要使用新的方法，降低使用成本
4、提供Web，AppID来管理对应的框架

仅仅是个人的观点

Jack

**Comment by shannonchou** [comment]
感谢 @xhzengAIB 的认可。
关于1，SwiftTheme 只打算专注于解决主题/皮肤问题
关于2，你是说提供网络下载、安装、管理主题的统一解决方案吗？
关于3，我们更倾向于添加方法而不是覆盖UIKit 的方法，避免带来不可预知的错误和安全性问题，也避免与其他框架造成冲突。
关于4，我们目前只想把SwiftTheme 作为主题工具框架来对待，暂时不考虑把它作为平台来发展

**Comment by xhzengAIB** [comment]
@shannonchou 感谢你的回复，我仅仅表达一下个人观点，现在已经做得很好了，已经有提供皮肤下载功能了。

覆盖UIKit的方法在很大程度上可以避免不可预知的错误，安全性的问题你能举一些例子吗？

因为我看到现在已经是通过runtime（https://github.com/jiecao-fm/SwiftTheme/blob/master/Source/NSObject%2BTheme.swift#L15）实现了，和直接覆盖UIKit的方法应该都是存在相关的问题的吧！

其实通过覆盖其方法主要的目的就是为了降低使用成本，例如不想用主题了，直接去掉pod，如果需要用主题那就保留pod，这样不需要修改任何代码就把该功能开启和屏蔽了

Jack

**Comment by fanweixiao** [comment]
:+1: to @shannonchou

**Comment by shannonchou** [comment]
@xhzengAIB   覆盖方法的确简化了用法，但剥夺了开发者们选择的权利，因为有些模块可能别人不想使用本框架。还有，如果其他开源框架也采用了覆盖UIKit 的方式，那么在一起使用时很容易发生冲突。
