### ISSUE TITLE
Swift 4 warning in ThemeCGFloatPicker.swift

### ISSUE THREAD

**Issue by n3d1117** [jiecao-fm/SwiftTheme#43]
<img width="866" alt="screen shot 2017-10-05 at 19 18 45" src="https://user-images.githubusercontent.com/11541888/31240800-2632b124-aa02-11e7-8de1-c1c2f6266434.png">

Hello, I get this warning in `ThemeCGFloatPicker.swift` after updating to Swift 4. Do you have any idea on how to get rid of it?

**Comment by wxxsw** [comment]
May won't fix this problem, because Swift 3.2 is a short version, will soon be replaced by Swift 4, you can directly use Swift 4 corresponding version `0.4.0` or temporarily ignore the warning.

If you think it is still important, please tell me. If not, please close this issue.

Thanks.

**Comment by n3d1117** [comment]
Thank you very much. Using `0.4.0` and it's gone now.
