### ISSUE TITLE
UIColor from ThemeColorPicker

### ISSUE THREAD

**Issue by YuryRadchenko** [jiecao-fm/SwiftTheme#46]
How get current UIColor from ThemeColorPicker ?

**Comment by wxxsw** [comment]
See https://github.com/jiecao-fm/SwiftTheme/issues/18.

**Comment by YuryRadchenko** [comment]
let navbarTitleColor = navbarTitleThemeColorPicker.value() as? UIColor
ERROR: Cannot invoke 'value' with no arguments

Swift 4

**Comment by wxxsw** [comment]
https://github.com/jiecao-fm/SwiftTheme/commit/b3eab93a51475314dee751d4798e003384801d5d Sorry, i have just fixed, please use the latest commit.

**Comment by YuryRadchenko** [comment]
Update SwiftTheme via Carthage but also Cannot invoke 'value' with no arguments.

**Comment by wxxsw** [comment]
I did not push a new version. Please use `github "jiecao-fm/SwiftTheme" "master"` in Cartfile.

**Comment by YuryRadchenko** [comment]
Work. Thank you.
