### ISSUE TITLE
Color of UITextField placeholder

### ISSUE THREAD

**Issue by elbracht** [jiecao-fm/SwiftTheme#47]
Is there a way to style the color of an UITextField placeholder text?

Without SwiftTheme I use the `attributedPlaceholder` to change the color.

**Comment by shannonchou** [comment]
Sorry for late reply.

SwiftTheme doesn't support it directly. But you can handle it by observing the notification.

Example:

```swift
NotificationCenter.default.addObserver(
	self, 
	selector: #selector(doSomethingMethod),
	name: NSNotification.Name(rawValue: ThemeUpdateNotification), 
	object: nil
)
```

```swift
func doSomethingMethod() {
        let themeIndex = ThemeManager.currentThemeIndex
        //do something according to `themeIndex`
}
```
