### ISSUE TITLE
编译出错了

### ISSUE THREAD

**Issue by marychenyuan** [jiecao-fm/SwiftTheme#5]
你好，我编译PlistDemo时出现编译错误，在NSObject+Theme.swift页面中提示：Expcted','separator。

我对swift不熟悉，请多指教，谢谢

**Comment by ryanlxc** [comment]
你是不是对源码做了修改？做了哪些修改？

**Comment by marychenyuan** [comment]
没有，直接下载后编译就失败了

**Comment by ryanlxc** [comment]
我这边没有问题，你可以试下重新下载编译，如果还有问题最好提供具体的错误日志

**Comment by shannonchou** [comment]
@marychenyuan 确认你的xcode 版本是否为7.3，老版本的xcode 是更早的swift 语法

**Comment by wxxsw** [comment]
@marychenyuan 

Swift2.2版本之前声明选择器的方法是 `Selector("someMethod")` 或者 `"someMethod"`，在Swift2.2之后语法改为了 `#selector(someMethod)`

例如你报错那行的代码是这样的：
`NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(_updateTheme), name: ThemeUpdateNotification, object: nil)`

如果你暂时不想升级Xcode，为了编译通过，你可以暂时将此处修改为旧的写法：
`NSNotificationCenter.defaultCenter().addObserver(self, selector: "_updateTheme", name: ThemeUpdateNotification, object: nil)`

😄

**Comment by marychenyuan** [comment]
谢谢你们的耐心指导！  确实是xcode未升级到7.3版本的问题。 升级后就正常运行了！

另外，是否能提供一份使用objective-c来调用这个框架的代码呢？  我现在急需使用换肤功能，觉得这套框架很适合放在我的项目中，但由于不熟悉swift所以有点力不从心。。。。
如果有示例的话我会更容易使用它！

**Comment by shannonchou** [comment]
把SwiftTheme 源代码拷贝到你的项目中，在.m 文件中引入 import "xxx-Swift.h"，这里的xxx 一般是你的target 名称，具体的看你项目的Build Settings 中的“Objective-C Generated Interface Header Name” 配置。

SwiftTheme 的OC 接口一般用法如下：
`lbl.theme_backgroundColor = [ThemeColorPicker pickerWithColors:@[@"#FAF9F9", @"#E2E2E2"]];`

**Comment by marychenyuan** [comment]
好的，非常感谢~

**Comment by wxxsw** [comment]
@marychenyuan 刚刚增加了Objective-C的[Demo](https://github.com/jiecao-fm/SwiftTheme/tree/master/OCDemo)

**Comment by marychenyuan** [comment]
好！麻烦了~！
