### ISSUE TITLE
textField.layer.theme_borderColor不生效

### ISSUE THREAD

**Issue by zhangnianqq** [jiecao-fm/SwiftTheme#54]
textField.layer.theme_borderColor = ThemeCGColorPicker(keyPath: " LogInColors.textFieldLineColor") 一直是黑色 但我文件设置的是白色； 
我这样设置就能生效：
if let colorString = ThemeManager.value(for: "LogInColors.textFieldLineColor") as? String {
            textField.layer.borderColor = UIColor.colorWithCSS(css: colorString).cgColor
        }
麻烦您看下

**Comment by wxxsw** [comment]
你的 " LogInColors.textFieldLineColor" 最前面多了个空格
