### ISSUE TITLE
Swift compiler warning

### ISSUE THREAD

**Issue by getaclue** [jiecao-fm/SwiftTheme#58]
Hey guys,

Thanks for creating this! Super useful!

Got a question: 
- is anyone is working on this?

![Swift compiler warning](https://cdn-pro.dprcdn.net/files/acc_603419/hNaX1f)

If not, I can see about submitting a PR? (Just didn't want to duplicate work in case someone already fixed it ^_^)

Thank you,
Alex

**Comment by wxxsw** [comment]
Hello @getaclue , this problem has been fixed in 1f7fb47c5c00baa5603300094f687e3454951bcd, thank you! 😄

**Comment by getaclue** [comment]
Oh okay, thanks for the quick response!!
