### ISSUE TITLE
how can i set button state?

### ISSUE THREAD

**Issue by lizizi** [jiecao-fm/SwiftTheme#59]
怎样给一个按钮 设置点击和正常不同状态的背景色？ 我用的是配置plist 的方式
how can i switch button's background color with diffrent state?

-------------------------
v.theme_backgroundColor = ""         没有设置状态的参数 ，，谢谢

**Comment by wxxsw** [comment]
UIButton 只支持设置不同状态的背景图片而不是背景，所以你可以通过这种方式来做：
```swift
let picker = ThemeImagePicker(keyPath: "someKeyPath") { v -> UIImage? in
    return UIColor(rgba: v as! String).toImage() // toImage() 方法需要你自己实现
}
UIButton().theme_setBackgroundImage(picker, forState: .normal)
```

**Comment by lizizi** [comment]
v.setBackgroundImage(UIColor.createImageWithColor(color: UIColor.blue), for: .normal)
如果平时是上面这样写的

可是实在不知道 怎样把字符转类型的参数关联起来

**Comment by lizizi** [comment]
谢谢 解决了 
let picker = ThemeImagePicker(keyPath: "loginOutBtnBg") { value -> UIImage? in
            
            var str = value as! String
            let index = str.index(str.startIndex, offsetBy: 1)
            let result = str.substring(from: index)
            
            return  UIColor.createImageWithColor(color: self.getColorWithHexString(hex: result))
        }

找了一个将16进制数字 转换成 uicolor 方法

**Comment by wxxsw** [comment]
棒~  这个库里面也有个现成的16进制颜色字符串转为 `UIColor` 的方法 `UIColor(rgba: String)`
