### ISSUE TITLE
UIButton methods cause error

### ISSUE THREAD

**Issue by dosymbaev** [jiecao-fm/SwiftTheme#65]
Whenever I try to use .theme_setImage() or .theme_setTitleColor() I get an error     
![nsobject theme swift 2018-03-26 13-13-41](https://user-images.githubusercontent.com/20577361/37891824-8e3b27b6-30f7-11e8-9363-1bafce7ebf1d.png)

I declare the button as:
button = UIButton(type: .custom)
button.theme_setImage("PanelView.button", forState: .normal)

**Comment by kcramer** [comment]
You didn't provide a stack trace or any other information, so I'm not sure what you are trying to do or what is going wrong.  However, it appears you are not calling the function with the expected parameters.  The function theme_setImage expects a ThemeImagePicker and not a string.  Usually you provide an array of image names or an actual ThemeImagePicker.

If you were trying to use the plist keypath option, then it seems likely that it isn't finding it for some reason.  It either is not finding the plist file or the keypath is wrong.  I don't use the plist option, but the PlistDemo shows a UIButton working correctly with theme_setTitleColor.

**Comment by kcramer** [comment]
Hopefully you were able to resolve the issue.  I'm closing this issue.  If you still have this issue, let me know.
