### ISSUE TITLE
How to use on a custom class?

### ISSUE THREAD

**Issue by n3d1117** [jiecao-fm/SwiftTheme#67]
Hello, I am using a library that provides a CustomClass (that doesn't inherit from any UIKit component) with a UIColor property in it. What is the best way to use SwiftTheme on it?

```
open class CustomClass {
   public var someColor: UIColor
}
```

I want to do:
```
extension CustomClass {
    var theme_someColor: ThemeColorPicker? {
        get { return getThemePicker(self, "setSomeColor:") as? ThemeColorPicker }
        set { setThemePicker(self, "setSomeColor:", newValue) }
    }
}
```

but `getThemePicker ` and `setThemePicker` are marked as private so I can't use them. Any idea? Thanks

**Comment by wxxsw** [comment]
Sorry, SwiftTheme only works on objects that inherit from NSObject because KVC is used.

Even if you have inherited NSObject, you also need a fork project to add your own extensions, `getThemePicker` and `setThemePicker` will remain private.

**Comment by n3d1117** [comment]
Thank you for your answer. Yes, the class inherits from NSObject so I think the best way is to fork the project and add my own extension.
