### ISSUE TITLE
displayP3Red Problem

### ISSUE THREAD

**Issue by crabman448** [jiecao-fm/SwiftTheme#68]
Hi!
We use your library in our project. 
We have LottieAnimation right under the navigation bar. The idea is that animation and navigation bar have the same colors.
I get UIColor for navigation bar like this `ThemeManager.color(for: "SomeColorKey")`. 
But I faced a problem, when the lottie and navigation bar colors were different. My color hex is `#2a78ba`. 
But then I replaced this function inside your library
```
    public convenience init(hex6: UInt32, alpha: CGFloat = 1) {
        let divisor = CGFloat(255)
        let red     = CGFloat((hex6 & 0xFF0000) >> 16) / divisor
        let green   = CGFloat((hex6 & 0x00FF00) >>  8) / divisor
        let blue    = CGFloat( hex6 & 0x0000FF       ) / divisor
        
        if #available(iOS 10.0, *) {
            self.init(displayP3Red: red, green: green, blue: blue, alpha: alpha)
        } else {
            self.init(red: red, green: green, blue: blue, alpha: alpha)
        }
    }
```
with this function
```
    public convenience init(hex6: UInt32, alpha: CGFloat = 1) {
        let divisor = CGFloat(255)
        let red     = CGFloat((hex6 & 0xFF0000) >> 16) / divisor
        let green   = CGFloat((hex6 & 0x00FF00) >>  8) / divisor
        let blue    = CGFloat( hex6 & 0x0000FF       ) / divisor
        
        self.init(red: red, green: green, blue: blue, alpha: alpha)
}
```
And the problem has gone. 
To be honest, I don't know, what the property `displayP3Red` does, but looks like I'm affected by it. If you have any suggestions why is it so, it would be awesome.
Thanks!

**Comment by macdrevx** [comment]
I was just impacted by this as well. SwiftTheme is making the assumption that if we're on iOS 10 or later, that we want to use the P3 color space. I don't like this assumption. The designer on my team works in the extended sRGB color space and specifies the colors for the developers in that color space. Now I'm it a bit of a tricky situation trying to find a way to work around this assumption in SwiftTheme.

**Comment by macdrevx** [comment]
@crabman448 here's the workaround I'm using. In my situation, I'm creating a ThemeColorPicker manually rather than pulling it from a plist, so I'm able to create the colors myself and avoid the P3 color space:

```
let colors = […create UIColors here…]
let colorPicker = ThemeColorPicker(v: { ThemeManager.element(for: colors) })
```

**Comment by crabman448** [comment]
@macdrevx thanks :) 
But actually in our project we removed SwiftTheme
