### ISSUE TITLE
UITabBarItem

### ISSUE THREAD

**Issue by lanchc** [jiecao-fm/SwiftTheme#78]
.tabBarItem.setTitleTextAttributes([NSAttributedString.Key.foregroundColor : UIColor.orange], for: UIControl.State.normal)
.tabBarItem.setTitleTextAttributes([NSAttributedString.Key.foregroundColor : UIColor.white], for: UIControl.State.selected)

这个怎么添加主题

**Comment by kcramer** [comment]
You would use:

tabBarItem.theme_setTitleTextAttributes(...)
