### ISSUE TITLE
Xcode10 编译错误

### ISSUE THREAD

**Issue by ibadcool** [jiecao-fm/SwiftTheme#79]
import Foundation
import UIKit
import SwiftTheme

class TestView: UIView {
    override init(frame: CGRect) {
        super.init(frame: frame)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

class TestButton: UIButton {
    
    override init(frame: CGRect) {
        super.init(frame: frame)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

TestButton init报错: Initializer does not override a designated initializer from its superclass
Incorrect argument label in call (have 'frame:', expected 'type:')

经查, 是 NSObject+Theme.swift  81行 
fileprivate typealias setValueForStateIMP       = @convention(c) (NSObject, Selector, AnyObject, UIControl.State) -> Void 导致的问题, 注释掉这行就编译通过了. UIControl.State

**Comment by kcramer** [comment]
I looked at it and moving the typealias declarations outside the extension solves the complication issue without breaking any functionality.  I submitted a PR for it.
