### ISSUE TITLE
theme_setStatusBarStyle doesn't work as expected

### ISSUE THREAD

**Issue by futantan** [jiecao-fm/SwiftTheme#9]
Hi, thanks for your awesome project, it helps me a lot. But I got a problem.
theme colour and images works well but the status bar doesn't change respond to `ThemeManager.setTheme`

I add code below in my `didFinishLaunchingWithOptions`

```swift
UIApplication.sharedApplication().theme_setStatusBarStyle(ThemeStatusBarStylePicker(styles: .Default, .LightContent), animated: true)
```

It doesn't work, anything else I need to do to change my status bar style?

**Comment by futantan** [comment]
OK, I get it.

```swift
Info.plist  -> View Controller-based status bar apperaence -> NO
```

You can add it to the README file 😂
Again, thanks for your awesome project!

**Comment by wxxsw** [comment]
Yes, Thank you for your remind! 
This is a common mistake, I will add this to the README :satisfied:

**Comment by DiwakarThapa** [comment]
@wxxsw hello I am facing similar issue on iOS 13 on swiftTheme 0.5.2. Everything is working great but statusBar is not working as expected. I also added `View Controller-based status bar apperaence -> NO to my info.plist` and `theme_setStatusBarStyle(ThemeStatusBarStylePicker(styles: .Default, .LightContent), animated: true)` in appDelegate

**Comment by wxxsw** [comment]
@DiwakarThapa You can try to run the `Demo`. I just tested, the status bar can be updated.

**Comment by DiwakarThapa** [comment]
@wxxsw  it tested on Demo and it is not working. In yellow theme, as shown in your video example in description it should turn status bar style to dark but it is white and also I am using iOS 14 sorry I mentioned iOS 13.

**Comment by kcramer** [comment]
Try ```theme_setStatusBarStyle(ThemeStatusBarStylePicker(styles: .DarkContent, .LightContent), animated: true)```.  Starting with iOS 13 I had to switch from .default to .darkContent to get it to work correctly.

**Comment by DiwakarThapa** [comment]
@kcramer thanks it worked.
